### ISSUE TITLE
CSS axis selectors followed by predicates ("foo > .bar") result in parser errors

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#131] opened 2015-07-29 14:46 UTC
Parsing CSS expressions such as `foo > .bar` and `foo>.bar` raises a parser error, this should be supported.

**Comment by abotalov** [comment] 2015-07-29 15:16
Duplicate of https://github.com/YorickPeterse/oga/issues/126

**Comment by YorickPeterse** [comment] 2015-07-29 20:12
@abotalov No, these are two separate issues. #126 is due to the lexer producing `T_SPACE` tokens where it shouldn't while this particular issue is due to the parser grammar being too strict.

**Comment by YorickPeterse** [comment] 2015-07-29 20:13
Regarding the grammar, the following is the problem: https://github.com/YorickPeterse/oga/blob/ed3cbe7975eeb9d142c4f649334038b6389abc0e/lib/oga/css/parser.rll#L101-L131

The `predicate` rule isn't allowed here even though it should be.

**Closed** 2015-09-04 14:07 UTC
Labels: Bug, CSS, Parser
