### ISSUE TITLE
Encoding HTML Entities

### ISSUE THREAD

**Issue by bryanp** [YorickPeterse/oga#148] opened 2016-02-21 21:30 UTC
I've hit an issue where not all HTML entities are being encoded properly.

```
irb#1(main):001:0> require 'oga'
=> true
irb#1(main):002:0> doc = Oga.parse_html('&copy;')
=> Document(
  children: NodeSet(Text("©"))
)
irb#1(main):003:0> doc.to_xml
=> "©"
```

I'd expect `doc.to_xml` to return `&copy;`.

After digging it appears that while `Oga::HTML::Entities` is used to decode, `Oga::XML::Entites` is used to encode. This creates a problem as the XML entities don't include the same entities defined in HTML. In fact, `Oga::HTML::Entities` doesn't have a way to encode.

We're replacing Nokogiri with Oga in Pakyow but are currently having to avoid the decode/encode issue (see https://github.com/pakyow/pakyow/commit/3a3532a5fbc60d6eb8cd318bfd3d72b20e05120c). It would be helpful if `Oga::HTML::Entities` had a way to encode. I believe adding this would be a step in the direction of supporting my initial use-case.

I don't mind adding this feature but wanted to ask for input first.

**Comment by YorickPeterse** [comment] 2016-02-21 21:55
This particular behaviour isn't exclusive to Oga, Nokogiri also does this:

    Nokogiri::HTML.fragment('<p>&copy;</p>').to_html

In what way does Pakyow depend on entities being encoded upon serializing a document back to XML/HTML? Since the list of HTML entities is rather big (around 2120-something entities) encoding all these might introduce a hefty performance penalty when serializing documents.

**Comment by bryanp** [comment] 2016-02-21 22:13
Yeah, entities in Pakyow have never worked right to date. We're trying to finally get it right :-)

We use Oga (and previously Nokogiri) only to parse an HTML document. From it we create an instance of `StringDoc`, which exposes only "significant" nodes as mutable. A `StringDoc` represents a document as arrays of strings, so the resulting render is essentially `flatten.join`. This makes rendering really fast.

The issue is that when we read the `text` of an element from Oga, the entities are decoded and we have no way of encoding them when converting a `StringDoc` back to an HTML string.

However, you're right that encoding 2,120 entities might hurt performance. Decoding doesn't do anything for us in 95% of use-cases. Give that, our best path forward (as far as Pakyow is concerned) might be to not decode and let the developer encode in cases where it's needed.

Since AFAIK right now the only way to avoid decoding is to monkey-patch a couple methods, would you be open to building in support for disabling decoding? I still think it would be nice to be able to encode HTML entities as well as decode, but even if that was supported we'd likely avoid using it in Pakyow.

Thanks for your response; hope we can find a good solution here!

**Comment by YorickPeterse** [comment] 2016-02-21 22:33
> The issue is that when we read the text of an element from Oga, the entities are decoded and we have no way of encoding them when converting a StringDoc back to an HTML string.

I'm not sure if I'm entirely following, but what exactly is the problem here with keeping the entities in their decoded form?

I just ran some basic benchmarks and it seems encoding the 2120-something explicitly listed HTML entities doesn't add much (if any) overhead over only encoding the XML entities.

Note that this particular list of entities only includes those I grabbed at some point from the HTML specification, it doesn't include hexadecimal/numeric entities. Encoding the latter upon serialization is something discussed in #133.

Since all HTML only (as in, excluding the XML ones such as `&gt;`) entities are valid both in their encoded and decoded form I don't really see a problem with keeping them in their decoded form upon serialization.

**Comment by YorickPeterse** [comment] 2016-02-21 22:35
To clarify, what exactly is the problem with these "StringDocs" containing lines such as "hello ©" instead of "hello &copy;" upon output?

**Comment by bryanp** [comment] 2016-02-21 22:38
The reason is when the document is rendered in the browser we want the encoded entities (I think). What got me going this direction was the fact that some entities (specifically `&copy;`, `&nbsp;`) render incorrectly in the browser with out of the box Oga.

![screenshot 2016-02-21 16 36 58](https://cloud.githubusercontent.com/assets/18920/13205938/65599b0e-d8b9-11e5-9cb6-6a54dbf229f6.png)

There's a no break space between the arrow and the text.

**Comment by YorickPeterse** [comment] 2016-02-21 23:12
@bryanp That seems to be the result of not setting the encoding to UTF8. For example, take the following Rack app:

```ruby
require 'rack'
require 'oga'

class MyApp
  def call(env)
    doc = Oga.parse_html('<p>hello&nbsp;&copy;</p>')

    [200, {'Content-Type' => 'text/html'}, [doc.to_xml]]
  end
end

run MyApp.new
```

This outputs the following in Chrome:

![timings](https://cloud.githubusercontent.com/assets/86065/13206154/e2ad3e50-d8f8-11e5-96f5-bb1046c4e6ee.png)

**Comment by bryanp** [comment] 2016-02-21 23:15
Huh, okay. Does Oga have its own encoding option? I set Ruby's encoding to UTF8 in this case :-/

**Comment by YorickPeterse** [comment] 2016-02-21 23:16
@bryanp No, Oga doesn't do anything special with encodings. Is there some standalone Pakyow application that reproduces the problem?

**Comment by bryanp** [comment] 2016-02-22 00:04
Here's an [example](https://github.com/bryanp/oga-pakyow). Start the server with `bundle exec pakyow s`. This is the important code: https://github.com/bryanp/oga-pakyow/blob/master/app/lib/routes.rb

![screenshot 2016-02-21 18 03 35](https://cloud.githubusercontent.com/assets/18920/13206537/70c520f6-d8c5-11e5-85ab-50b9c8cbf386.png)

I've bypassed all the `StringDoc` complexity to try and get to the heart of the issue.

**Comment by bryanp** [comment] 2016-02-22 00:14
Bleh, so it appears to be a browser issue. Explicitly setting the charset to UTF-8 makes it work.

**Comment by YorickPeterse** [comment] 2016-02-22 09:36
@bryanp Is there a way Pakyow can solve this problem for users, or does it require them to explicitly add a `meta` tag to specify the encoding? The latter is pretty common anyway so I don't think it should be a problem, though I can see it as being a bit of an odd requirement.

**Comment by bryanp** [comment] 2016-02-22 13:26
It requires the user to explicitly add a `meta` tag. What I don't like about it is we're changing their markup, then requiring the user to take another step to work around it. Pakyow could add the tag automatically, but I don't know how I feel about that.

**Comment by YorickPeterse** [comment] 2016-02-22 13:59
@bryanp Like I said I can add this to Oga, but there are a few issues I have with it:

1. It would only take care of the HTML entities explicitly listed, entities such as `&#x....` would be left as-is as encoding these is going to be too slow. In turn I'm not a fan of providing something that only solves a portion of the problem.
2. It feels unnecessary. That is, `&copy;` and `©` are both valid in the context of HTML so there's no real benefit to using `&copy;` over `©` in output. 
3. If the output is something containing Unicode characters then the corresponding encoding should be compatible with this. In the case of browsers this can be done by either adding a meta-tag or by the user defaulting to UTF-8 (which isn't a very practical solution). I'd argue it's not unreasonable to tell users that if they want to display Unicode characters they have to add a `meta` tag with the appropriate encoding.

This basically leaves us with the following options:

1. Oga encodes known Unicode characters as their entity equivalents upon generating XML/HTML, ignoring characters produced using hexadecimal/numeric entities. Because this only solves a small part of the problem I'm not a fan of this.
2. Pakyow tells its users that if they want to output Unicode characters they have to add a `meta` tag with the appropriate encoding. This won't (or at least shouldn't) require any code changes in either project.

**Comment by bryanp** [comment] 2016-02-22 14:53
I think we'll move forward with Option 2. The user might find it odd that we're changing their markup, but the reason why seems pretty clear-cut and easy to explain. Generated apps will include the `meta` tag and we'll consider presenting a warning in development if the `meta` tag is missing. We're targeting less experienced users, so we have to make things really straight-forward.

Thanks for taking the time to discuss this, it was quite helpful!

**Comment by YorickPeterse** [comment] 2016-02-22 15:01
@bryanp OK, I'll close this issue then.

**Closed by YorickPeterse** 2016-02-22 15:01 UTC
Labels: Entity Conversion, HTML

**Comment by omninonsense** [comment] 2016-02-22 16:24
@bryanp Slightly offtopic, wouldn't it be wiser to send a `Content-Type: text/html; charset=utf-8` header&mdash;provided that you have control over the headers being sent&mdash;instead of having using a `meta` tag. Since, the latter in some cases might cause the browser to discard the current DOM and start re-parsing the content all over again, although I forgot what triggers it specifically.

**Comment by bryanp** [comment] 2016-02-22 18:33
@omninonsense Yep, you're probably right. I'll look into this a bit more. Thanks for pointing it out 😄
